/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KirunEditor {
        "gridSize": string;
        "theme": string;
    }
}
declare global {
    interface HTMLKirunEditorElement extends Components.KirunEditor, HTMLStencilElement {
    }
    var HTMLKirunEditorElement: {
        prototype: HTMLKirunEditorElement;
        new (): HTMLKirunEditorElement;
    };
    interface HTMLElementTagNameMap {
        "kirun-editor": HTMLKirunEditorElement;
    }
}
declare namespace LocalJSX {
    interface KirunEditor {
        "gridSize"?: string;
        "theme"?: string;
    }
    interface IntrinsicElements {
        "kirun-editor": KirunEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kirun-editor": LocalJSX.KirunEditor & JSXBase.HTMLAttributes<HTMLKirunEditorElement>;
        }
    }
}
